# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_sanatci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanatci',
            name='ilgilendigi_bolum',
            field=models.IntegerField(choices=[(1, 'Resim'), (2, 'Heykel'), (3, 'Muzik'), (4, 'Tiyatro')]),
        ),
    ]
