# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_auto_20170205_1345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kisi',
            table='kisi_tables',
        ),
    ]
